export interface ContractGeneratorSchema {
  name: string
  directory?: string
  description?: string
  dependencies?: string[]
  entities?: string[] | string // Can be array or JSON string from CLI
  includeCQRS?: boolean
  tags?: string

  /**
   * Package containing database entity types generated by prisma-effect-kysely.
   * When specified, the contract library imports entity types from this package
   * instead of generating its own (avoiding duplication).
   *
   * @example "@myorg/types-database"
   */
  typesDatabasePackage?: string

  // Dotfile generation options (Effect.ts code quality enforcement)
  // Only library-specific dotfiles (eslint.config.mjs, tsconfig.json) are added
  addDotfiles?: boolean // Default: true
  overwriteDotfiles?: boolean // Default: false
}
