name: Setup
description: Perform standard setup and install dependencies using Bun.
inputs:
  bun-version:
    description: The version of Bun to install
    required: true
    default: latest

runs:
  using: composite
  steps:
    - name: Install Bun
      uses: oven-sh/setup-bun@v2
      with:
        bun-version: ${{ inputs.bun-version }}
    - name: Install dependencies
      shell: bash
      run: bun install
