packages:
  - .
  - libs/**
  - apps/**

catalog:
  '@effect/platform': ^0.72.5
  '@effect/platform-node': ^0.66.5
  '@effect/rpc': ^0.50.0
  '@effect/rpc-http': ^0.49.0
  '@effect/schema': ^0.75.5
  '@supabase/supabase-js': ^2.47.10
  effect: ^3.12.5
  ioredis: ^5.8.2
  kysely: ^0.27.5
  pg: ^8.13.1
