/**
 * User Domain Events
 *
 * Defines all domain events for user domain operations.
 *
 * @generated This file was generated by monorepo-library-generator
 */
import { Schema } from "effect";
// ============================================================================
// Base Event Metadata
// ============================================================================

/**
 * Standard metadata for all events
 */
export const EventMetadata = Schema.Struct({
  /** Unique event identifier (auto-generated by database if not provided) */
  eventId: Schema.optional(Schema.UUID).annotations({
    title: "Event ID",
    description: "Unique identifier for this event - auto-generated by database"
  }),
  /** Event type identifier */
  eventType: Schema.String.annotations({
    title: "Event Type",
    description: "Name of the event type"
  }),
  /** Event version for schema evolution */
  eventVersion: Schema.Literal("1.0").annotations({
    title: "Event Version",
    description: "Event schema version for evolution"
  }),
  /** Timestamp when event occurred (defaults to current time) */
  occurredAt: Schema.optionalWith(Schema.Date, { default: () => new Date() }).annotations({
    title: "Occurred At",
    description: "UTC timestamp when the event occurred"
  }),
  /** Optional correlation ID for tracing */
  correlationId: Schema.optional(Schema.UUID).annotations({
    title: "Correlation ID",
    description: "ID to correlate related events across services"
  }),
  /** Optional causation ID (ID of event that caused this one) */
  causationId: Schema.optional(Schema.UUID).annotations({
    title: "Causation ID",
    description: "ID of the event that caused this event"
  })
}).pipe(
  Schema.annotations({
    identifier: "EventMetadata",
    title: "Event Metadata"
  })
)

export type EventMetadata = typeof EventMetadata.Type
// ============================================================================
// Aggregate Metadata
// ============================================================================

/**
 * User aggregate metadata for event sourcing
 *
 * Includes aggregate root ID and version for optimistic concurrency.
 */
export const UserAggregateMetadata = Schema.Struct({
  /** Aggregate root identifier */
  aggregateId: Schema.String.pipe(Schema.brand("UserId")).annotations({
    title: "User ID",
    description: "ID of the user aggregate root"
  }),
  /** Aggregate version for optimistic concurrency */
  aggregateVersion: Schema.Number.annotations({
    title: "Aggregate Version",
    description: "Version number for optimistic locking"
  })
}).pipe(
  Schema.annotations({
    identifier: "UserAggregateMetadata",
    title: "User Aggregate Metadata"
  })
)

export type UserAggregateMetadata = typeof UserAggregateMetadata.Type
// ============================================================================
// User Domain Events
// ============================================================================

/**
 * Event emitted when a new user is created
 */
export class UserCreatedEvent extends Schema.Class<UserCreatedEvent>("UserCreatedEvent")({
  /** Event metadata */
  metadata: EventMetadata,
  /** Aggregate metadata */
  aggregate: UserAggregateMetadata,
  /** Event payload - the created user data */
  payload: Schema.Struct({
    // TODO: Add fields for the created user
    id: Schema.String.pipe(Schema.brand("UserId")),
    createdAt: Schema.Date
  })
}) { }

/**
 * Event emitted when a user is updated
 */
export class UserUpdatedEvent extends Schema.Class<UserUpdatedEvent>("UserUpdatedEvent")({
  /** Event metadata */
  metadata: EventMetadata,
  /** Aggregate metadata */
  aggregate: UserAggregateMetadata,
  /** Event payload - the changes made */
  payload: Schema.Struct({
    // TODO: Add fields that were updated
    id: Schema.String.pipe(Schema.brand("UserId")),
    updatedAt: Schema.Date,
    changes: Schema.Record({ key: Schema.String, value: Schema.Unknown })
  })
}) { }

/**
 * Event emitted when a user is deleted
 */
export class UserDeletedEvent extends Schema.Class<UserDeletedEvent>("UserDeletedEvent")({
  /** Event metadata */
  metadata: EventMetadata,
  /** Aggregate metadata */
  aggregate: UserAggregateMetadata,
  /** Event payload */
  payload: Schema.Struct({
    id: Schema.String.pipe(Schema.brand("UserId")),
    deletedAt: Schema.Date
  })
}) { }
// ============================================================================
// Event Union Types
// ============================================================================

/**
 * Union of all User domain events
 */
export type UserEvent =
  | UserCreatedEvent
  | UserUpdatedEvent
  | UserDeletedEvent

/**
 * Schema for all User events (for serialization)
 */
export const UserEventSchema = Schema.Union(
  UserCreatedEvent,
  UserUpdatedEvent,
  UserDeletedEvent
)
// ============================================================================
// Event Factory Helpers
// ============================================================================

/**
 * Create event metadata with defaults
 */
export function createEventMetadata(
  eventType: string,
  options?: {
    correlationId?: string
    causationId?: string
  }
) {
  return {
    eventType,
    eventVersion: "1.0",
    occurredAt: new Date(),
    ...(options?.correlationId && { correlationId: options.correlationId }),
    ...(options?.causationId && { causationId: options.causationId })
  } satisfies EventMetadata
}

/**
 * Create aggregate metadata
 *
 * Note: aggregateId is branded at the call site via Schema validation
 */
export function createAggregateMetadata(
  aggregateId: UserAggregateMetadata["aggregateId"],
  aggregateVersion: number
) {
  return {
    aggregateId,
    aggregateVersion
  } satisfies UserAggregateMetadata
}
