/**
 * User Ports (Interfaces)
 *
 * Defines repository and service interfaces for user domain.
 *
 * @generated This file was generated by monorepo-library-generator
 */
import type { UserSelect as User } from "@samuelho-dev/types-database";
import { Context } from "effect";
import type { Effect, Option } from "effect";
import type { UserRepositoryError } from "./errors";
// ============================================================================
// Supporting Types
// ============================================================================
/** Filter options for querying users */
export interface UserFilters {
  readonly createdAfter?: Date;
  readonly createdBefore?: Date;
  readonly updatedAfter?: Date;
  readonly updatedBefore?: Date;
}

/** Offset-based pagination parameters (for repository layer) */
export interface OffsetPaginationParams {
  readonly limit: number;
  readonly offset: number;
}

/** Sort options */
export interface SortOptions {
  readonly field: string;
  readonly direction: "asc" | "desc";
}

/**
 * Paginated result with generic item type
 */
export interface PaginatedResult<T> {
  readonly items: readonly T[]
  readonly total: number
  readonly limit: number
  readonly offset: number
  readonly hasMore: boolean
}
// ============================================================================
// Repository Port
// ============================================================================
/**
 * UserRepository Context Tag for dependency injection
 *
 * Effect 3.0+ pattern: Context.Tag with inline interface definition.
 * This ensures proper type inference and avoids recursive type issues.
 */
export class UserRepository extends Context.Tag("@samuelho-dev/contract-user/UserRepository")<
  UserRepository,
  {
    /** Find user by ID */
    readonly findById: (id: string) => Effect.Effect<Option.Option<User>, UserRepositoryError, never>
    /** Find all users matching filters */
    readonly findAll: (filters?: UserFilters, pagination?: OffsetPaginationParams, sort?: SortOptions) => Effect.Effect<PaginatedResult<User>, UserRepositoryError>
    /** Count users matching filters */
    readonly count: (filters?: UserFilters) => Effect.Effect<number, UserRepositoryError, never>
    /** Create a new user */
    readonly create: (input: Partial<User>) => Effect.Effect<User, UserRepositoryError, never>
    /** Update an existing user */
    readonly update: (id: string, input: Partial<User>) => Effect.Effect<User, UserRepositoryError, never>
    /** Delete a user permanently */
    readonly delete: (id: string) => Effect.Effect<void, UserRepositoryError, never>
    /** Check if user exists by ID */
    readonly exists: (id: string) => Effect.Effect<boolean, UserRepositoryError, never>
  }
>() {
}
// ============================================================================
// Service Port
// ============================================================================
/**
 * UserService Context Tag for dependency injection
 *
 * Effect 3.0+ pattern: Context.Tag with inline interface definition.
 */
export class UserService extends Context.Tag("@samuelho-dev/contract-user/UserService")<
  UserService,
  {
    /** Get user by ID */
    readonly get: (id: string) => Effect.Effect<User, UserRepositoryError, never>
    /** List users with filters and pagination */
    readonly list: (filters?: UserFilters, pagination?: OffsetPaginationParams, sort?: SortOptions) => Effect.Effect<PaginatedResult<User>, UserRepositoryError, never>
    /** Create a new user */
    readonly create: (input: Partial<User>) => Effect.Effect<User, UserRepositoryError, never>
    /** Update an existing user */
    readonly update: (id: string, input: Partial<User>) => Effect.Effect<User, UserRepositoryError, never>
    /** Delete a user */
    readonly delete: (id: string) => Effect.Effect<void, UserRepositoryError, never>
  }
>() {
}
